 drop table if exists phone CASCADE;
 drop table if exists user CASCADE;
 create table phone (
       id_phone bigint generated by default as identity,
        city_code varchar(255) not null,
        country_code varchar(255) not null,
        number varchar(255) not null,
        id_user binary not null,
        primary key (id_phone)
    );
create table user (
       id_user binary not null,
        created timestamp not null,
        email varchar(255) not null,
        is_active boolean not null,
        last_login timestamp,
        modified timestamp,
        name varchar(100) not null,
        password varchar(255) not null,
        token varchar(1000),
        primary key (id_user)
    );
    alter table user 
       add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table phone 
       add constraint FKbtclsgmcq82gwkcwm7ms1ginv 
       foreign key (id_user) 
       references user;